-- =====================================================================
-- PROJETO CRIPTO - FASE 5
-- Script DDL (Create, Alter, Drop)
-- Equipe: Fabio de Souza Junior, Gianluca Rodrigues Cordeiro,
--         Guilherme Moura Badia, Michael Molinari, Pedro Vitor Boeloni Baier
-- =====================================================================

-- =====================================================================
-- DROP (ordem inversa de dependencia, com tratamento de erro -942)
-- =====================================================================

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE T_SIP_TRANSACAO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE T_SIP_ATIVO_CRIPTO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE T_SIP_CARTEIRA CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE T_SIP_EMPRESA CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE T_SIP_INVESTIDOR CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE T_SIP_USUARIO CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN
         RAISE;
      END IF;
END;
/

-- =====================================================================
-- CREATE (ordem direta de dependencia)
-- =====================================================================

CREATE TABLE T_SIP_USUARIO (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY
                   CONSTRAINT PK_SIP_USUARIO PRIMARY KEY,
    nm_usuario     VARCHAR2(100) NOT NULL,
    ds_email       VARCHAR2(100) NOT NULL
                   CONSTRAINT UN_SIP_USUARIO_EMAIL UNIQUE,
    ds_senha_hash  VARCHAR2(256) NOT NULL
);

CREATE TABLE T_SIP_INVESTIDOR (
    id_usuario NUMBER
        CONSTRAINT PK_SIP_INVESTIDOR PRIMARY KEY
        CONSTRAINT FK_SIP_INVESTIDOR_USER REFERENCES T_SIP_USUARIO(id)
);

CREATE TABLE T_SIP_EMPRESA (
    id_empresa       NUMBER GENERATED BY DEFAULT AS IDENTITY
                     CONSTRAINT PK_SIP_EMPRESA PRIMARY KEY,
    nm_razao_social  VARCHAR2(150) NOT NULL,
    nr_cnpj          CHAR(14) NOT NULL
                     CONSTRAINT UN_SIP_EMPRESA_CNPJ UNIQUE,
    id_usuario       NUMBER NOT NULL
                     CONSTRAINT FK_SIP_EMPRESA_USER REFERENCES T_SIP_USUARIO(id)
);

CREATE TABLE T_SIP_CARTEIRA (
    id_carteira           NUMBER GENERATED BY DEFAULT AS IDENTITY
                          CONSTRAINT PK_SIP_CARTEIRA PRIMARY KEY,
    vl_saldo_total_geral  NUMBER(15,2) NOT NULL,
    id_investidor         NUMBER NOT NULL,
    id_empresa            NUMBER NOT NULL,
    CONSTRAINT FK_SIP_CARTEIRA_INVEST FOREIGN KEY (id_investidor) REFERENCES T_SIP_INVESTIDOR(id_usuario),
    CONSTRAINT FK_SIP_CARTEIRA_EMP FOREIGN KEY (id_empresa) REFERENCES T_SIP_EMPRESA(id_empresa)
);

CREATE TABLE T_SIP_ATIVO_CRIPTO (
    id_carteira            NUMBER NOT NULL,
    sg_ticker              VARCHAR2(10) NOT NULL,
    qt_ativo               NUMBER(18,8) NOT NULL,
    vl_preco_medio_compra  NUMBER(15,2) NOT NULL,
    vl_total_investido     NUMBER(15,2) NOT NULL,
    CONSTRAINT PK_SIP_ATIVO_CRIPTO PRIMARY KEY (id_carteira, sg_ticker),
    CONSTRAINT FK_SIP_ATIVO_CARTEIRA FOREIGN KEY (id_carteira) REFERENCES T_SIP_CARTEIRA(id_carteira)
);

CREATE TABLE T_SIP_TRANSACAO (
    id_transacao        NUMBER GENERATED BY DEFAULT AS IDENTITY
                        CONSTRAINT PK_SIP_TRANSACAO PRIMARY KEY,
    dt_data_hora        DATE NOT NULL,
    tp_transacao        VARCHAR2(20) NOT NULL
                        CONSTRAINT CH_SIP_TRANSACAO CHECK (tp_transacao = 'COMPRA' OR tp_transacao = 'VENDA'),
    qt_transacao        NUMBER(16,8) NOT NULL,
    vl_unitario         NUMBER(15,2) NOT NULL,
    ds_hash_blockchain  VARCHAR2(64)
                        CONSTRAINT UN_SIP_TRANSACAO_HASH UNIQUE,
    id_carteira         NUMBER NOT NULL,
    CONSTRAINT FK_SIP_TRANS_CARTEIRA FOREIGN KEY (id_carteira) REFERENCES T_SIP_CARTEIRA(id_carteira)
);

-- =====================================================================
-- ALTER (evolucao de regra de negocio / dado cadastral adicional)
-- =====================================================================

ALTER TABLE T_SIP_TRANSACAO
    ADD CONSTRAINT CH_SIP_VL_UNITARIO CHECK (vl_unitario > 0);

ALTER TABLE T_SIP_USUARIO
    ADD (cpf_usuario CHAR(11) NOT NULL CONSTRAINT UN_SIP_USUARIO_CPF UNIQUE);
